export const ActionTypes = {
  CREATE_WORKFORCE_MEMBER: 'CREATE_WORKFORCE_MEMBER',
  UPDATE_WORKFORCE_STATUS: 'UPDATE_WORKFORCE_STATUS',
  ASSIGN_WORKFORCE_TO_SHIFT: 'ASSIGN_WORKFORCE_TO_SHIFT',
  SCHEDULE_ASSET_MAINTENANCE: 'SCHEDULE_ASSET_MAINTENANCE',
  UPDATE_ASSET_STATUS: 'UPDATE_ASSET_STATUS',
  CREATE_WORK_ORDER: 'CREATE_WORK_ORDER',
  UPDATE_WORK_ORDER_PRIORITY: 'UPDATE_WORK_ORDER_PRIORITY',
  CREATE_SHIFT: 'CREATE_SHIFT',
  UPDATE_SHIFT_CAPACITY: 'UPDATE_SHIFT_CAPACITY',
  ESCALATE_INCIDENT: 'ESCALATE_INCIDENT',
  RESOLVE_INCIDENT: 'RESOLVE_INCIDENT',
  ASSIGN_INCIDENT: 'ASSIGN_INCIDENT',
  CREATE_ASSIGNMENT: 'CREATE_ASSIGNMENT',
  RELEASE_ASSIGNMENT: 'RELEASE_ASSIGNMENT',
  SEND_NOTIFICATION: 'SEND_NOTIFICATION',
  ALERT_SUPERVISOR: 'ALERT_SUPERVISOR',
  CONNECT_STRIPE: 'CONNECT_STRIPE',
  RUN_SHOPIFY_SYNC: 'RUN_SHOPIFY_SYNC',
} as const;

export const ACTION_EXECUTION_MAX_RETRIES = 3;
