'use client';

import React, { useState } from 'react';
import { 
  Activity, 
  Search, 
  RefreshCw,
} from 'lucide-react';
import { PageHeader } from '@/components/layout/page-header';
import { LoadingState } from '@/components/layout/loading-state';
import { ErrorState } from '@/components/layout/error-state';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useActions, useApproveAction, useRejectAction, useRecordOutcome } from '@/hooks/queries/use-ai-command-center';
import { ActionExecutionCard } from './action-execution-card';
import { useDemoContext } from '@/hooks/use-demo-context';
import { useAuth } from '@/hooks/use-auth';
import { cn } from '@/lib/utils';
import { ActionExecutionView } from '@/types/ai';

export function ActionsScreen() {
  const activeContext = useDemoContext();
  const { user } = useAuth();
  const organizationId = activeContext.selectedOrganizationId ?? user?.organizationId;
  
  const { data: response, isLoading, isError, refetch } = useActions({ organizationId });
  const approveMutation = useApproveAction();
  const rejectMutation = useRejectAction();
  const outcomeMutation = useRecordOutcome();
  
  const [filter, setFilter] = useState('ALL');
  const [searchQuery, setSearchQuery] = useState('');

  if (isLoading) {
    return <LoadingState title="Loading actions..." description="Retrieving recent and pending AI executions." />;
  }

  if (isError) {
    return <ErrorState title="Error loading actions" description="We couldn't retrieve the execution history." onRetry={refetch} />;
  }

  const actions = response ?? [];
  
  const filteredActions = actions.filter((action: ActionExecutionView) => {
    const matchesFilter = filter === 'ALL' || action.status === filter;
    const matchesSearch = action.type.toLowerCase().includes(searchQuery.toLowerCase()) || 
                         (action.proposal?.title || '').toLowerCase().includes(searchQuery.toLowerCase());
    return matchesFilter && matchesSearch;
  });

  const handleApprove = async (id: string) => {
    await approveMutation.mutateAsync({ id, organizationId });
  };

  const handleReject = async (id: string) => {
    await rejectMutation.mutateAsync({ id, organizationId });
  };

  const handleFeedback = async (id: string, type: 'POSITIVE' | 'NEGATIVE') => {
    await outcomeMutation.mutateAsync({ 
      executionId: id, 
      outcomeType: type,
      outcomeScore: type === 'POSITIVE' ? 1.0 : -1.0,
      notes: type === 'POSITIVE' ? 'Operator feedback: this helped.' : 'Operator feedback: not useful.',
    });
  };

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="AI Operators"
        title="Execution Engine"
        description="Monitor and approve autonomous actions generated by the Nexora intelligence layer."
      />

      <div className="flex flex-col md:flex-row gap-4 items-center justify-between bg-white/5 p-4 rounded-2xl border border-white/10">
        <div className="flex items-center gap-4 w-full md:w-auto">
          <div className="flex flex-wrap gap-2">
            {[
              { value: 'ALL', label: 'All' },
              { value: 'PENDING_APPROVAL', label: 'Pending' },
              { value: 'COMPLETED', label: 'Completed' },
              { value: 'FAILED', label: 'Failed' },
            ].map((option) => (
              <Button
                key={option.value}
                type="button"
                variant="outline"
                size="sm"
                className={cn(
                  'border-white/10 bg-black/20 text-slate-300',
                  filter === option.value && 'border-[var(--brand-500)] bg-[var(--brand-500)]/10 text-white',
                )}
                onClick={() => setFilter(option.value)}
              >
                {option.label}
              </Button>
            ))}
          </div>
        </div>

        <div className="flex items-center gap-2 w-full md:w-auto">
          <div className="relative w-full md:w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
            <Input
              placeholder="Search actions..."
              className="pl-10 bg-black/20 border-white/10"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          <Button variant="outline" size="sm" className="border-white/10 px-3" onClick={() => refetch()}>
            <RefreshCw className={cn("h-4 w-4", (isLoading) && "animate-spin")} />
          </Button>
        </div>
      </div>

      {filteredActions.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center bg-white/[0.02] rounded-3xl border border-dashed border-white/10">
          <Activity className="h-12 w-12 text-slate-600 mb-4" />
          <h3 className="text-lg font-medium text-white">No actions found</h3>
          <p className="text-slate-500 max-w-xs mx-auto mt-2">
            {searchQuery || filter !== 'ALL' 
              ? "Try adjusting your filters or search query."
              : "AI agents haven't proposed or executed any actions yet."}
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredActions.map((action) => (
            <ActionExecutionCard
              key={action.id}
              execution={action}
              onApprove={handleApprove}
              onReject={handleReject}
              onFeedback={handleFeedback}
              showDetails={true}
            />
          ))}
        </div>
      )}
    </div>
  );
}
