import {
  NotificationCategory,
  NotificationSeverity,
  OperationalIncidentStatus,
  OperationalZoneType,
  WorkOrderPriority,
  WorkOrderStatus,
  WorkflowTaskStatus,
} from '@prisma/client';

import type { CompanySeedBlueprint } from '../shared/seed-helpers';

export const LOGISTICS_COMPANY_BLUEPRINT: CompanySeedBlueprint = {
  packKey: 'LOGISTICS',
  packNamespace: 'logistics-company',
  organization: {
    name: 'Helix Logistics Operations',
    slug: 'helix-logistics',
  },
  departments: [
    {
      code: 'OPS',
      name: 'Operations',
      description: 'Runs daily operational coordination and shift execution.',
    },
    {
      code: 'FIELD',
      name: 'Field Workforce',
      description: 'Executes field jobs, inspections, and service coverage.',
    },
    {
      code: 'MAINT',
      name: 'Maintenance',
      description: 'Maintains operational asset readiness and maintenance planning.',
    },
  ],
  positions: [
    {
      code: 'OPS-SUP',
      title: 'Operations Supervisor',
      departmentCode: 'OPS',
      description: 'Leads shift operations and exception response.',
      gradeLevel: 'Supervisor',
    },
    {
      code: 'FIELD-OP',
      title: 'Field Operator',
      departmentCode: 'FIELD',
      description: 'Executes operational jobs and field tasks.',
      gradeLevel: 'Specialist',
    },
    {
      code: 'FIELD-TECH',
      title: 'Field Technician',
      departmentCode: 'FIELD',
      description: 'Handles inspections, maintenance, and field remediation.',
      gradeLevel: 'Technician',
    },
    {
      code: 'MAINT-LEAD',
      title: 'Maintenance Lead',
      departmentCode: 'MAINT',
      description: 'Coordinates maintenance work intake and execution.',
      gradeLevel: 'Lead',
    },
  ],
  team: [
    {
      key: 'ops-supervisor',
      firstName: 'Samira',
      lastName: 'Khan',
      email: 'samira.khan@helix-logistics.demo',
      phoneNumber: '+12025550300',
      departmentCode: 'OPS',
      positionCode: 'OPS-SUP',
      roleCodes: ['TEAM_MANAGER'],
      engagementStartDate: new Date('2021-07-08T00:00:00.000Z'),
      skills: ['shift-coordination', 'incident-triage'],
    },
    {
      key: 'field-operator-1',
      firstName: 'Owen',
      lastName: 'Mills',
      email: 'owen.mills@helix-logistics.demo',
      phoneNumber: '+12025550301',
      departmentCode: 'FIELD',
      positionCode: 'FIELD-OP',
      roleCodes: ['PLATFORM_OPERATOR'],
      engagementStartDate: new Date('2022-02-14T00:00:00.000Z'),
      skills: ['field-operations', 'equipment-handling'],
      license: {
        identifierValue: 'HLX-LIC-0001',
        issuedAt: new Date('2023-01-10T00:00:00.000Z'),
        expiresAt: new Date('2027-01-10T00:00:00.000Z'),
        issuingAuthority: 'Regional Field Operations Board',
      },
    },
    {
      key: 'field-operator-2',
      firstName: 'Maya',
      lastName: 'Scott',
      email: 'maya.scott@helix-logistics.demo',
      phoneNumber: '+12025550302',
      departmentCode: 'FIELD',
      positionCode: 'FIELD-OP',
      roleCodes: ['PLATFORM_OPERATOR'],
      engagementStartDate: new Date('2023-05-22T00:00:00.000Z'),
      skills: ['coverage', 'safety-checks'],
      license: {
        identifierValue: 'HLX-LIC-0002',
        issuedAt: new Date('2023-06-01T00:00:00.000Z'),
        expiresAt: new Date('2027-06-01T00:00:00.000Z'),
        issuingAuthority: 'Regional Field Operations Board',
      },
    },
    {
      key: 'field-technician-1',
      firstName: 'Theo',
      lastName: 'Nguyen',
      email: 'theo.nguyen@helix-logistics.demo',
      phoneNumber: '+12025550303',
      departmentCode: 'FIELD',
      positionCode: 'FIELD-TECH',
      roleCodes: ['PLATFORM_OPERATOR'],
      engagementStartDate: new Date('2020-10-19T00:00:00.000Z'),
      skills: ['inspection', 'maintenance'],
      license: {
        identifierValue: 'HLX-LIC-0003',
        issuedAt: new Date('2022-03-11T00:00:00.000Z'),
        expiresAt: new Date('2026-12-31T00:00:00.000Z'),
        issuingAuthority: 'Regional Field Operations Board',
      },
    },
    {
      key: 'maintenance-lead',
      firstName: 'Elena',
      lastName: 'Ford',
      email: 'elena.ford@helix-logistics.demo',
      phoneNumber: '+12025550304',
      departmentCode: 'MAINT',
      positionCode: 'MAINT-LEAD',
      roleCodes: ['TEAM_MANAGER'],
      engagementStartDate: new Date('2019-09-02T00:00:00.000Z'),
      skills: ['maintenance-planning', 'asset-readiness'],
      license: {
        identifierValue: 'HLX-LIC-0004',
        issuedAt: new Date('2021-07-01T00:00:00.000Z'),
        expiresAt: new Date('2026-07-01T00:00:00.000Z'),
        issuingAuthority: 'Regional Field Operations Board',
      },
    },
  ],
  zones: [
    {
      code: 'REG-CENTRAL',
      name: 'Central Region',
      type: OperationalZoneType.REGION,
      description: 'Primary regional control area for daily operations.',
    },
    {
      code: 'FIELD-EAST',
      name: 'East Field Territory',
      type: OperationalZoneType.TERRITORY,
      description: 'Field territory handling service delivery and inspections.',
      parentCode: 'REG-CENTRAL',
    },
    {
      code: 'MAINT-HUB',
      name: 'Maintenance Hub',
      type: OperationalZoneType.FACILITY,
      description: 'Maintenance planning and staging facility.',
      parentCode: 'REG-CENTRAL',
    },
  ],
  workflows: [
    {
      key: 'asset-readiness-review',
      definitionCode: 'logistics.asset-readiness-review',
      definitionName: 'Asset Readiness Review',
      definitionDescription: 'Reviews readiness of assets before deployment.',
      moduleKey: 'operations',
      entityType: 'asset',
      entityId: 'AST-OPS-001',
      createdByMemberKey: 'maintenance-lead',
      task: {
        key: 'readiness-check',
        title: 'Review asset readiness packet',
        description: 'Validate readiness checklist before assignment.',
        status: WorkflowTaskStatus.IN_PROGRESS,
        assigneeMemberKey: 'maintenance-lead',
      },
    },
  ],
  assets: [
    {
      code: 'AST-OPS-001',
      name: 'Regional Service Van',
      assetType: 'VEHICLE',
      assetClass: 'Utility Van',
      serialNumber: 'HLX-VEH-1001',
      registrationNumber: 'OPS-2301',
      zoneCode: 'FIELD-EAST',
    },
    {
      code: 'AST-OPS-002',
      name: 'Inspection Tablet',
      assetType: 'DEVICE',
      assetClass: 'Rugged Tablet',
      serialNumber: 'HLX-DEV-2101',
      zoneCode: 'FIELD-EAST',
    },
    {
      code: 'AST-OPS-003',
      name: 'Dock Lift Platform',
      assetType: 'EQUIPMENT',
      assetClass: 'Lift Platform',
      serialNumber: 'HLX-EQP-3301',
      zoneCode: 'MAINT-HUB',
    },
  ],
  workOrders: [
    {
      code: 'LOG-WO-001',
      title: 'Morning field coverage dispatch',
      description: 'Coordinate coverage for the morning field operations block.',
      workType: 'FIELD_SERVICE',
      status: WorkOrderStatus.ACTIVE,
      priority: WorkOrderPriority.HIGH,
      createdByMemberKey: 'ops-supervisor',
      zoneCode: 'FIELD-EAST',
      sourceType: 'schedule',
      sourceId: 'shift-east-01',
    },
    {
      code: 'LOG-WO-002',
      title: 'Asset readiness remediation',
      description: 'Resolve readiness issues before next deployment window.',
      workType: 'ASSET_READINESS',
      status: WorkOrderStatus.READY,
      priority: WorkOrderPriority.CRITICAL,
      createdByMemberKey: 'maintenance-lead',
      zoneCode: 'MAINT-HUB',
      sourceType: 'workflow',
      sourceId: 'asset-readiness-review',
    },
    {
      code: 'LOG-WO-003',
      title: 'Field site inspection',
      description: 'Perform a field inspection for a newly onboarded service site.',
      workType: 'SITE_INSPECTION',
      status: WorkOrderStatus.PLANNED,
      priority: WorkOrderPriority.MEDIUM,
      createdByMemberKey: 'field-technician-1',
      zoneCode: 'FIELD-EAST',
    },
  ],
  incidents: [
    {
      code: 'LOG-INC-001',
      title: 'Coverage gap on east territory',
      description: 'A scheduled operator called out during a high-demand window.',
      incidentType: 'STAFFING_GAP',
      severity: 'HIGH',
      status: OperationalIncidentStatus.IN_PROGRESS,
      zoneCode: 'FIELD-EAST',
      workOrderCode: 'LOG-WO-001',
      workforceMemberKey: 'field-operator-1',
      reportedByMemberKey: 'ops-supervisor',
      assignedToMemberKey: 'maintenance-lead',
      actionSummary: 'Escalated to maintenance and supervisor coverage pool.',
    },
    {
      code: 'LOG-INC-002',
      title: 'Asset failed readiness review',
      description: 'A service van failed readiness review due to inspection issues.',
      incidentType: 'ASSET_FAILURE',
      severity: 'MEDIUM',
      status: OperationalIncidentStatus.OPEN,
      zoneCode: 'MAINT-HUB',
      workOrderCode: 'LOG-WO-002',
      assetCode: 'AST-OPS-001',
      reportedByMemberKey: 'maintenance-lead',
      assignedToMemberKey: 'field-technician-1',
      actionSummary: 'Assigned remediation follow-up to field technician.',
    },
  ],
  notifications: [
    {
      key: 'coverage-gap-alert',
      recipientMemberKey: 'ops-supervisor',
      category: NotificationCategory.INCIDENT,
      severity: NotificationSeverity.WARNING,
      title: 'Field coverage gap detected',
      message: 'A high-severity staffing gap is active in East Field Territory.',
      entityType: 'incident',
      entityId: 'LOG-INC-001',
    },
    {
      key: 'asset-readiness-alert',
      recipientMemberKey: 'maintenance-lead',
      category: NotificationCategory.COMPLIANCE,
      severity: NotificationSeverity.INFO,
      title: 'Asset readiness review needs action',
      message: 'A readiness remediation work order is ready for execution.',
      entityType: 'work_order',
      entityId: 'LOG-WO-002',
    },
  ],
  domainEvents: [
    {
      key: 'coverage-gap-signal',
      eventType: 'operations.coverage_gap.detected',
      aggregateType: 'work_order',
      aggregateId: 'LOG-WO-001',
      actorMemberKey: 'ops-supervisor',
      sourceModule: 'operations',
      payload: {
        territory: 'FIELD-EAST',
        severity: 'high',
      },
    },
  ],
  enrichments: {
    tenancy: 'logistics',
    connectors: 'logistics',
    observability: 'logistics',
    aiPlatform: 'logistics',
  },
};
