import {
  ApprovalDecisionType,
  ApprovalRequestStatus,
  ApprovalStepStatus,
  NotificationCategory,
  NotificationSeverity,
  WorkOrderPriority,
  WorkOrderStatus,
  WorkflowTaskStatus,
} from '@prisma/client';

import type { CompanySeedBlueprint } from '../shared/seed-helpers';

export const REVOPS_COMPANY_BLUEPRINT: CompanySeedBlueprint = {
  packKey: 'REVOPS',
  packNamespace: 'revops-company',
  organization: {
    name: 'Mercury Revenue Operations',
    slug: 'mercury-revops',
  },
  departments: [
    {
      code: 'SALES',
      name: 'Sales',
      description: 'Runs deal pipeline and commercial execution.',
    },
    {
      code: 'MKT',
      name: 'Marketing',
      description: 'Creates demand generation, campaigns, and funnel signals.',
    },
    {
      code: 'PART',
      name: 'Partnerships',
      description: 'Owns strategic partnerships and channel collaboration.',
    },
  ],
  positions: [
    {
      code: 'AE',
      title: 'Account Executive',
      departmentCode: 'SALES',
      description: 'Owns enterprise deal progression and customer negotiation.',
      gradeLevel: 'Specialist',
    },
    {
      code: 'SDR',
      title: 'Sales Development Representative',
      departmentCode: 'SALES',
      description: 'Generates qualified pipeline and early opportunity intake.',
      gradeLevel: 'Specialist',
    },
    {
      code: 'MKT-AN',
      title: 'Marketing Analyst',
      departmentCode: 'MKT',
      description: 'Tracks campaign performance and revenue signals.',
      gradeLevel: 'Analyst',
    },
    {
      code: 'PART-MGR',
      title: 'Partnerships Manager',
      departmentCode: 'PART',
      description: 'Coordinates channel relationships and commercial programs.',
      gradeLevel: 'Manager',
    },
  ],
  team: [
    {
      key: 'revops-manager',
      firstName: 'Sofia',
      lastName: 'Turner',
      email: 'sofia.turner@mercury-revops.demo',
      phoneNumber: '+12025550400',
      departmentCode: 'SALES',
      positionCode: 'AE',
      roleCodes: ['TEAM_MANAGER'],
      engagementStartDate: new Date('2020-06-15T00:00:00.000Z'),
      skills: ['deal-desk', 'revenue-forecasting'],
    },
    {
      key: 'account-exec',
      firstName: 'Caleb',
      lastName: 'Brooks',
      email: 'caleb.brooks@mercury-revops.demo',
      phoneNumber: '+12025550401',
      departmentCode: 'SALES',
      positionCode: 'AE',
      roleCodes: ['PLATFORM_OPERATOR'],
      engagementStartDate: new Date('2022-04-11T00:00:00.000Z'),
      skills: ['enterprise-sales', 'deal-execution'],
    },
    {
      key: 'sdr',
      firstName: 'Mila',
      lastName: 'Rivera',
      email: 'mila.rivera@mercury-revops.demo',
      phoneNumber: '+12025550402',
      departmentCode: 'SALES',
      positionCode: 'SDR',
      roleCodes: ['PLATFORM_OPERATOR'],
      engagementStartDate: new Date('2023-07-10T00:00:00.000Z'),
      skills: ['lead-qualification', 'outbound'],
    },
    {
      key: 'marketing-analyst',
      firstName: 'Ethan',
      lastName: 'Ross',
      email: 'ethan.ross@mercury-revops.demo',
      phoneNumber: '+12025550403',
      departmentCode: 'MKT',
      positionCode: 'MKT-AN',
      roleCodes: ['PLATFORM_OPERATOR'],
      engagementStartDate: new Date('2021-09-21T00:00:00.000Z'),
      skills: ['campaign-attribution', 'signal-analysis'],
    },
    {
      key: 'partnerships-manager',
      firstName: 'Hannah',
      lastName: 'Cole',
      email: 'hannah.cole@mercury-revops.demo',
      phoneNumber: '+12025550404',
      departmentCode: 'PART',
      positionCode: 'PART-MGR',
      roleCodes: ['TEAM_MANAGER'],
      engagementStartDate: new Date('2021-02-08T00:00:00.000Z'),
      skills: ['channel-programs', 'co-selling'],
    },
  ],
  workflows: [
    {
      key: 'deal-approval',
      definitionCode: 'revops.deal-approval',
      definitionName: 'Deal Approval Workflow',
      definitionDescription: 'Routes strategic deal review before final commitment.',
      moduleKey: 'revops',
      entityType: 'deal',
      entityId: 'deal-enterprise-301',
      createdByMemberKey: 'account-exec',
      task: {
        key: 'prepare-deal-desk-brief',
        title: 'Prepare deal desk brief',
        description: 'Compile commercial details and risk context.',
        status: WorkflowTaskStatus.COMPLETED,
        assigneeMemberKey: 'revops-manager',
      },
      approval: {
        title: 'Approve strategic enterprise deal',
        description: 'Approve final pricing and strategic deal posture.',
        requestedByMemberKey: 'account-exec',
        status: ApprovalRequestStatus.APPROVED,
        step: {
          key: 'revops-approval',
          title: 'Revenue operations approval',
          approverMemberKey: 'revops-manager',
          status: ApprovalStepStatus.APPROVED,
          decisionType: ApprovalDecisionType.APPROVE,
          decisionComment: 'Approved within allowed pricing and margin limits.',
        },
      },
    },
    {
      key: 'discount-approval',
      definitionCode: 'revops.discount-approval',
      definitionName: 'Discount Approval Workflow',
      definitionDescription: 'Routes discount requests through revenue controls.',
      moduleKey: 'revops',
      entityType: 'deal',
      entityId: 'deal-discount-411',
      createdByMemberKey: 'account-exec',
      task: {
        key: 'review-discount-request',
        title: 'Review discount request',
        description: 'Validate strategic fit and pipeline health before approval.',
        status: WorkflowTaskStatus.IN_PROGRESS,
        assigneeMemberKey: 'revops-manager',
      },
      approval: {
        title: 'Approve discount exception',
        description: 'Discount exception requires revenue operations review.',
        requestedByMemberKey: 'account-exec',
        status: ApprovalRequestStatus.IN_PROGRESS,
        step: {
          key: 'revops-review',
          title: 'Revenue operations review',
          approverMemberKey: 'revops-manager',
          status: ApprovalStepStatus.PENDING,
        },
      },
    },
  ],
  workOrders: [
    {
      code: 'REV-WO-001',
      title: 'Review strategic enterprise deal desk package',
      description: 'Review commercial posture, pricing, and approval completeness.',
      workType: 'DEAL_DESK_REVIEW',
      status: WorkOrderStatus.ACTIVE,
      priority: WorkOrderPriority.HIGH,
      createdByMemberKey: 'revops-manager',
      sourceType: 'deal',
      sourceId: 'deal-enterprise-301',
    },
    {
      code: 'REV-WO-002',
      title: 'Lead quality anomaly investigation',
      description: 'Investigate sudden funnel quality decline from a new campaign.',
      workType: 'PIPELINE_ANALYSIS',
      status: WorkOrderStatus.READY,
      priority: WorkOrderPriority.MEDIUM,
      createdByMemberKey: 'marketing-analyst',
      sourceType: 'lead',
      sourceId: 'lead-q4-campaign-12',
    },
  ],
  notifications: [
    {
      key: 'deal-approved',
      recipientMemberKey: 'account-exec',
      category: NotificationCategory.APPROVAL,
      severity: NotificationSeverity.INFO,
      title: 'Strategic deal approved',
      message: 'Revenue operations approved the enterprise deal package.',
      entityType: 'deal',
      entityId: 'deal-enterprise-301',
    },
    {
      key: 'discount-review-pending',
      recipientMemberKey: 'revops-manager',
      category: NotificationCategory.APPROVAL,
      severity: NotificationSeverity.WARNING,
      title: 'Discount exception requires review',
      message: 'A discount exception remains pending revenue operations review.',
      entityType: 'deal',
      entityId: 'deal-discount-411',
    },
  ],
  domainEvents: [
    {
      key: 'lead-scored',
      eventType: 'revops.lead.scored',
      aggregateType: 'lead',
      aggregateId: 'lead-q4-campaign-12',
      actorMemberKey: 'marketing-analyst',
      sourceModule: 'revops-intelligence',
      payload: {
        score: 82,
        model: 'campaign-propensity-v2',
      },
    },
    {
      key: 'discount-requested',
      eventType: 'revops.discount.requested',
      aggregateType: 'deal',
      aggregateId: 'deal-discount-411',
      actorMemberKey: 'account-exec',
      sourceModule: 'deal-desk',
      payload: {
        requestedDiscountPercent: 18,
        dealValue: 96000,
      },
    },
  ],
  enrichments: {
    tenancy: 'revops',
    connectors: 'revops',
    observability: 'revops',
    aiPlatform: 'revops',
  },
};
