import {
  ApprovalDecisionType,
  ApprovalRequestStatus,
  ApprovalStepStatus,
  NotificationCategory,
  NotificationSeverity,
  OperationalIncidentStatus,
  WorkOrderPriority,
  WorkOrderStatus,
  WorkflowTaskStatus,
} from '@prisma/client';

import type { CompanySeedBlueprint } from '../shared/seed-helpers';

export const SAAS_COMPANY_BLUEPRINT: CompanySeedBlueprint = {
  packKey: 'SAAS',
  packNamespace: 'saas-company',
  organization: {
    name: 'Northstar SaaS Operations',
    slug: 'northstar-saas',
  },
  departments: [
    {
      code: 'ENG',
      name: 'Engineering',
      description: 'Builds, operates, and ships product capabilities.',
    },
    {
      code: 'PRD',
      name: 'Product',
      description: 'Owns roadmap planning, prioritization, and requirements.',
    },
    {
      code: 'SAL',
      name: 'Sales',
      description: 'Runs pipeline execution and commercial growth.',
    },
    {
      code: 'CS',
      name: 'Customer Success',
      description: 'Handles customer adoption, support, and escalations.',
    },
  ],
  positions: [
    {
      code: 'ENG-DEV',
      title: 'Software Engineer',
      departmentCode: 'ENG',
      description: 'Builds and maintains platform capabilities.',
      gradeLevel: 'Engineer',
    },
    {
      code: 'PRD-MGR',
      title: 'Product Manager',
      departmentCode: 'PRD',
      description: 'Owns requirements and release coordination.',
      gradeLevel: 'Manager',
    },
    {
      code: 'SAL-AE',
      title: 'Account Executive',
      departmentCode: 'SAL',
      description: 'Runs strategic deal progression and customer conversations.',
      gradeLevel: 'Specialist',
    },
    {
      code: 'CS-SUP',
      title: 'Support Specialist',
      departmentCode: 'CS',
      description: 'Handles customer issues and platform guidance.',
      gradeLevel: 'Specialist',
    },
  ],
  team: [
    {
      key: 'eng-lead',
      firstName: 'Ava',
      lastName: 'Chen',
      email: 'ava.chen@northstar-saas.demo',
      phoneNumber: '+12025550200',
      departmentCode: 'ENG',
      positionCode: 'ENG-DEV',
      roleCodes: ['TEAM_MANAGER'],
      engagementStartDate: new Date('2021-04-12T00:00:00.000Z'),
      skills: ['architecture', 'release-management'],
    },
    {
      key: 'frontend-dev',
      firstName: 'Marco',
      lastName: 'Silva',
      email: 'marco.silva@northstar-saas.demo',
      phoneNumber: '+12025550201',
      departmentCode: 'ENG',
      positionCode: 'ENG-DEV',
      roleCodes: ['PLATFORM_OPERATOR'],
      engagementStartDate: new Date('2022-08-03T00:00:00.000Z'),
      skills: ['frontend', 'customer-workflows'],
    },
    {
      key: 'product-manager',
      firstName: 'Priya',
      lastName: 'Nair',
      email: 'priya.nair@northstar-saas.demo',
      phoneNumber: '+12025550202',
      departmentCode: 'PRD',
      positionCode: 'PRD-MGR',
      roleCodes: ['TEAM_MANAGER'],
      engagementStartDate: new Date('2020-11-09T00:00:00.000Z'),
      skills: ['roadmap', 'requirements'],
    },
    {
      key: 'sales-rep',
      firstName: 'Jordan',
      lastName: 'Lee',
      email: 'jordan.lee@northstar-saas.demo',
      phoneNumber: '+12025550203',
      departmentCode: 'SAL',
      positionCode: 'SAL-AE',
      roleCodes: ['PLATFORM_OPERATOR'],
      engagementStartDate: new Date('2023-01-16T00:00:00.000Z'),
      skills: ['pipeline-management', 'enterprise-sales'],
    },
    {
      key: 'support-agent',
      firstName: 'Noah',
      lastName: 'Bennett',
      email: 'noah.bennett@northstar-saas.demo',
      phoneNumber: '+12025550204',
      departmentCode: 'CS',
      positionCode: 'CS-SUP',
      roleCodes: ['PLATFORM_OPERATOR'],
      engagementStartDate: new Date('2023-03-20T00:00:00.000Z'),
      skills: ['customer-support', 'triage'],
    },
  ],
  workflows: [
    {
      key: 'feature-approval',
      definitionCode: 'saas.feature-approval',
      definitionName: 'Feature Approval Workflow',
      definitionDescription: 'Routes a product feature for prioritization and implementation approval.',
      moduleKey: 'product-ops',
      entityType: 'project',
      entityId: 'proj-customer-insights-dashboard',
      createdByMemberKey: 'product-manager',
      task: {
        key: 'engineering-review',
        title: 'Engineering feasibility review',
        description: 'Review feasibility and delivery sequencing.',
        status: WorkflowTaskStatus.COMPLETED,
        assigneeMemberKey: 'eng-lead',
      },
      approval: {
        title: 'Approve feature release',
        description: 'Approve release of customer insights dashboard.',
        requestedByMemberKey: 'product-manager',
        status: ApprovalRequestStatus.APPROVED,
        step: {
          key: 'manager-approval',
          title: 'Engineering manager approval',
          approverMemberKey: 'eng-lead',
          status: ApprovalStepStatus.APPROVED,
          decisionType: ApprovalDecisionType.APPROVE,
          decisionComment: 'Approved for the next release train.',
        },
      },
    },
    {
      key: 'bug-escalation',
      definitionCode: 'saas.bug-escalation',
      definitionName: 'Bug Escalation Workflow',
      definitionDescription: 'Escalates high-priority defects affecting customer experience.',
      moduleKey: 'support-ops',
      entityType: 'ticket',
      entityId: 'ticket-bug-1042',
      createdByMemberKey: 'support-agent',
      task: {
        key: 'triage-defect',
        title: 'Triage customer-impacting bug',
        description: 'Coordinate triage across support, product, and engineering.',
        status: WorkflowTaskStatus.IN_PROGRESS,
        assigneeMemberKey: 'product-manager',
      },
    },
    {
      key: 'customer-issue-handling',
      definitionCode: 'saas.customer-issue-handling',
      definitionName: 'Customer Issue Handling Workflow',
      definitionDescription: 'Coordinates customer issue handling and service recovery.',
      moduleKey: 'customer-success',
      entityType: 'ticket',
      entityId: 'ticket-customer-224',
      createdByMemberKey: 'support-agent',
      task: {
        key: 'customer-follow-up',
        title: 'Coordinate customer follow-up',
        description: 'Confirm mitigation status and communicate recovery plan.',
        status: WorkflowTaskStatus.PENDING,
        assigneeMemberKey: 'support-agent',
      },
    },
  ],
  workOrders: [
    {
      code: 'SAAS-WO-001',
      title: 'Ship feature approval package',
      description: 'Coordinate release notes, QA signoff, and internal communications.',
      workType: 'INTERNAL_PROJECT',
      status: WorkOrderStatus.ACTIVE,
      priority: WorkOrderPriority.HIGH,
      createdByMemberKey: 'product-manager',
      sourceType: 'workflow',
      sourceId: 'feature-approval',
    },
    {
      code: 'SAAS-WO-002',
      title: 'Resolve premium customer bug ticket',
      description: 'Drive triage and mitigation for a premium customer issue.',
      workType: 'CUSTOMER_TICKET',
      status: WorkOrderStatus.READY,
      priority: WorkOrderPriority.CRITICAL,
      createdByMemberKey: 'support-agent',
      sourceType: 'ticket',
      sourceId: 'ticket-bug-1042',
    },
    {
      code: 'SAAS-WO-003',
      title: 'Prepare expansion account plan',
      description: 'Coordinate internal project work for upcoming expansion opportunity.',
      workType: 'ACCOUNT_PROJECT',
      status: WorkOrderStatus.PLANNED,
      priority: WorkOrderPriority.MEDIUM,
      createdByMemberKey: 'sales-rep',
      sourceType: 'manual',
      sourceId: 'expansion-plan-31',
    },
  ],
  incidents: [
    {
      code: 'SAAS-INC-001',
      title: 'Customer escalation for delayed rollout',
      description: 'A strategic customer reported blocked rollout due to a provisioning issue.',
      incidentType: 'CUSTOMER_ESCALATION',
      severity: 'HIGH',
      status: OperationalIncidentStatus.OPEN,
      workOrderCode: 'SAAS-WO-002',
      workforceMemberKey: 'support-agent',
      reportedByMemberKey: 'support-agent',
      assignedToMemberKey: 'eng-lead',
      actionSummary: 'Escalated to engineering and product review.',
    },
  ],
  notifications: [
    {
      key: 'feature-approval-ready',
      recipientMemberKey: 'product-manager',
      category: NotificationCategory.WORKFLOW,
      severity: NotificationSeverity.INFO,
      title: 'Feature approval workflow moved forward',
      message: 'The customer insights dashboard feature passed engineering review.',
      entityType: 'project',
      entityId: 'proj-customer-insights-dashboard',
    },
    {
      key: 'bug-escalation-open',
      recipientMemberKey: 'eng-lead',
      category: NotificationCategory.INCIDENT,
      severity: NotificationSeverity.WARNING,
      title: 'Premium customer bug escalation opened',
      message: 'A critical premium customer issue requires engineering action.',
      entityType: 'ticket',
      entityId: 'ticket-bug-1042',
    },
  ],
  domainEvents: [
    {
      key: 'feature-approved-event',
      eventType: 'product.feature.approval_ready',
      aggregateType: 'project',
      aggregateId: 'proj-customer-insights-dashboard',
      actorMemberKey: 'product-manager',
      sourceModule: 'product-ops',
      payload: {
        stage: 'engineering-review-complete',
        priority: 'high',
      },
    },
  ],
  enrichments: {
    tenancy: 'saas',
    connectors: 'saas',
    observability: 'saas',
    aiPlatform: 'saas',
  },
};
