# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4566b577a78db3750efe00c1cbe18ad"
name = "Nexora"
application_url = "https://reflections-prohibited-paint-routing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://reflections-prohibited-paint-routing.trycloudflare.com/api/v1/integrations/shopify/callback"
]

[sidekick]
extensions_summary = "Provide Nexora commerce insights and support tools for Shopify merchants"
